[package]
name    = "no_durability_damage"
version = "1.0.0"
edition = "2024"

[dependencies]
common  = { path = "../common" }
windows = { workspace = true }
winapi  = { workspace = true }

[lib]
crate-type = ["cdylib"]
name       = "ds3_no_durability_damage"