[package]
name    = "no_souls_loss"
version = "1.0.0"
edition = "2024"

[dependencies]
windows = { workspace = true }
common  = { path = "../common" }

[lib]
crate-type = ["cdylib"]
name       = "ds3_no_souls_loss"